# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_pwd', models.CharField(max_length=70)),
                ('user_mail', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=11)),
                ('user_addr', models.CharField(max_length=50)),
                ('user_code', models.CharField(max_length=10)),
                ('user_recv', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
