"""empty message

Revision ID: 02b807fbaacb
Revises: 3be65e491a23
Create Date: 2018-02-25 14:17:50.857073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b807fbaacb'
down_revision = '3be65e491a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collect_ibfk_1', 'collect', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('collect_ibfk_1', 'collect', 'course', ['course_id'], ['course_id'])
    # ### end Alembic commands ###
