"""empty message

Revision ID: 1117745a1d24
Revises: a23ba58e149c
Create Date: 2018-02-28 16:19:22.557834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1117745a1d24'
down_revision = 'a23ba58e149c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cancel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancel')
    # ### end Alembic commands ###
