"""empty message

Revision ID: 126c69911a6d
Revises: 02b807fbaacb
Create Date: 2018-02-25 14:33:45.747571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126c69911a6d'
down_revision = '02b807fbaacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('teacher_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'teacher_num')
    # ### end Alembic commands ###
