"""empty message

Revision ID: 1d298abc605c
Revises: 1117745a1d24
Create Date: 2018-03-03 14:45:36.550413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d298abc605c'
down_revision = '1117745a1d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('alipay', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'alipay')
    # ### end Alembic commands ###
