"""empty message

Revision ID: 2b59999dd743
Revises: 59d8146f754b
Create Date: 2018-01-31 15:25:48.133173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b59999dd743'
down_revision = '59d8146f754b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('user_logs', sa.String(length=128), nullable=True))
    op.drop_constraint('log_ibfk_1', 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'user', ['user_logs'], ['username'])
    op.drop_column('log', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('user', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key('log_ibfk_1', 'log', 'user', ['user'], ['username'])
    op.drop_column('log', 'user_logs')
    # ### end Alembic commands ###
