"""empty message

Revision ID: 2cda7182a5a2
Revises: 
Create Date: 2018-02-24 15:44:47.255495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cda7182a5a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course', 'school', ['school_name'], ['school_name'])
    op.drop_column('course', 'teachers_names')
    op.drop_column('course', 'teacher_names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('teacher_names', mysql.VARCHAR(length=512), nullable=True))
    op.add_column('course', sa.Column('teachers_names', mysql.VARCHAR(length=512), nullable=True))
    op.drop_constraint(None, 'course', type_='foreignkey')
    # ### end Alembic commands ###
