"""empty message

Revision ID: 30fdf491dfe1
Revises: 1d298abc605c
Create Date: 2018-03-03 14:52:43.923493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fdf491dfe1'
down_revision = '1d298abc605c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pay_remark', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pay_remark')
    # ### end Alembic commands ###
