"""empty message

Revision ID: 36d9122b496d
Revises: 998914334245
Create Date: 2018-02-02 09:39:40.702387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d9122b496d'
down_revision = '998914334245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('sales', sa.Integer(), nullable=True))
    op.add_column('goods', sa.Column('skull_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'skull_num')
    op.drop_column('goods', 'sales')
    # ### end Alembic commands ###
