"""empty message

Revision ID: 3be65e491a23
Revises: 095fa00dbf00
Create Date: 2018-02-24 15:55:58.191787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be65e491a23'
down_revision = '095fa00dbf00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course', 'teacher', ['teacher_name'], ['teacher_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    # ### end Alembic commands ###
