"""empty message

Revision ID: 442426be7e30
Revises: 56532620b7c7
Create Date: 2018-02-03 14:18:36.011149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442426be7e30'
down_revision = '56532620b7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('address', table_name='address')
    op.drop_index('area', table_name='address')
    op.drop_index('city', table_name='address')
    op.drop_index('phone', table_name='address')
    op.drop_index('province', table_name='address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('province', 'address', ['province'], unique=True)
    op.create_index('phone', 'address', ['phone'], unique=True)
    op.create_index('city', 'address', ['city'], unique=True)
    op.create_index('area', 'address', ['area'], unique=True)
    op.create_index('address', 'address', ['address'], unique=True)
    # ### end Alembic commands ###
