"""empty message

Revision ID: 47287729d4fe
Revises: 2b59999dd743
Create Date: 2018-01-31 15:28:21.453740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47287729d4fe'
down_revision = '2b59999dd743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###
