"""empty message

Revision ID: 4a030b170bbe
Revises: df878fa9671a
Create Date: 2018-02-01 14:40:40.528529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a030b170bbe'
down_revision = 'df878fa9671a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('count', sa.Column('order_num', sa.Integer(), nullable=True))
    op.add_column('count', sa.Column('today_order', sa.Integer(), nullable=True))
    op.add_column('count', sa.Column('today_vip', sa.Integer(), nullable=True))
    op.add_column('count', sa.Column('view_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('count', 'view_num')
    op.drop_column('count', 'today_vip')
    op.drop_column('count', 'today_order')
    op.drop_column('count', 'order_num')
    # ### end Alembic commands ###
