"""empty message

Revision ID: 59d8146f754b
Revises: 
Create Date: 2018-01-31 15:14:52.078413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d8146f754b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=128), nullable=True),
    sa.Column('ip_add', sa.String(length=32), nullable=True),
    sa.Column('add_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
