"""empty message

Revision ID: 6ddf68b7a120
Revises: e4626fc6b126
Create Date: 2018-02-28 15:47:31.414952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ddf68b7a120'
down_revision = 'e4626fc6b126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_ibfk_2', 'orders', type_='foreignkey')
    op.drop_column('orders', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_ibfk_2', 'orders', 'course', ['course_id'], ['course_id'])
    # ### end Alembic commands ###
