"""empty message

Revision ID: 6f257e660285
Revises: cb39479c90bd
Create Date: 2018-02-24 15:50:32.383902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f257e660285'
down_revision = 'cb39479c90bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_ibfk_2', 'course', type_='foreignkey')
    op.drop_column('course', 'school_name')
    op.add_column('teacher', sa.Column('teacher_company', sa.String(length=512), nullable=True))
    op.create_foreign_key(None, 'teacher', 'school', ['teacher_company'], ['school_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'teacher_company')
    op.add_column('course', sa.Column('school_name', mysql.VARCHAR(length=512), nullable=True))
    op.create_foreign_key('course_ibfk_2', 'course', 'school', ['school_name'], ['school_name'])
    # ### end Alembic commands ###
