"""empty message

Revision ID: 73aeb9e18f7b
Revises: 47287729d4fe
Create Date: 2018-01-31 15:46:17.794717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73aeb9e18f7b'
down_revision = '47287729d4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('pwd', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pwd')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
