"""empty message

Revision ID: 801bf2094c8f
Revises: 6f257e660285
Create Date: 2018-02-24 15:52:25.832150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801bf2094c8f'
down_revision = '6f257e660285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'teacher', ['teacher_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='unique')
    # ### end Alembic commands ###
