"""empty message

Revision ID: 814c0b501ebb
Revises: 36d9122b496d
Create Date: 2018-02-02 09:41:40.246125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814c0b501ebb'
down_revision = '36d9122b496d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('get_secure', sa.String(length=256), nullable=True))
    op.add_column('goods', sa.Column('share_link', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'share_link')
    op.drop_column('goods', 'get_secure')
    # ### end Alembic commands ###
