"""empty message

Revision ID: 9783b0fe6290
Revises: e6e10137400a
Create Date: 2018-02-27 16:56:55.438806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9783b0fe6290'
down_revision = 'e6e10137400a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('chapter_name', sa.String(length=512), nullable=True),
    sa.Column('long_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter')
    # ### end Alembic commands ###
