"""empty message

Revision ID: 9909d7ae85eb
Revises: 1ab65edd0894
Create Date: 2018-02-26 16:27:05.910342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9909d7ae85eb'
down_revision = '1ab65edd0894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_mess', sa.Integer(), nullable=True))
    op.drop_constraint('message_ibfk_1', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['user_mess'], ['id'])
    op.drop_column('message', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_ibfk_1', 'message', 'user', ['user'], ['id'])
    op.drop_column('message', 'user_mess')
    # ### end Alembic commands ###
