"""empty message

Revision ID: 998914334245
Revises: 4a030b170bbe
Create Date: 2018-02-01 16:21:17.545666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998914334245'
down_revision = '4a030b170bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('target', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'target')
    # ### end Alembic commands ###
