"""empty message

Revision ID: bd503414c9e9
Revises: a872290727d0
Create Date: 2018-02-27 15:53:33.461582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd503414c9e9'
down_revision = 'a872290727d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('add_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'add_time')
    # ### end Alembic commands ###
