"""empty message

Revision ID: c7db57066cdb
Revises: 814c0b501ebb
Create Date: 2018-02-02 09:47:51.519407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7db57066cdb'
down_revision = '814c0b501ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('image', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'goods', ['image'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods', type_='unique')
    op.drop_column('goods', 'image')
    # ### end Alembic commands ###
