"""empty message

Revision ID: cb39479c90bd
Revises: 2cda7182a5a2
Create Date: 2018-02-24 15:48:51.093309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb39479c90bd'
down_revision = '2cda7182a5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teacher_ibfk_1', 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'teacher_company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('teacher_company', mysql.VARCHAR(length=512), nullable=True))
    op.create_foreign_key('teacher_ibfk_1', 'teacher', 'school', ['teacher_company'], ['school_name'])
    # ### end Alembic commands ###
