"""empty message

Revision ID: d0cbfa7b8956
Revises: 9783b0fe6290
Create Date: 2018-02-28 15:01:09.589545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0cbfa7b8956'
down_revision = '9783b0fe6290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('chapter_name', sa.String(length=512), nullable=True),
    sa.Column('long_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chapter')
    op.add_column('orders', sa.Column('times', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'times')
    op.create_table('chapter',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('course', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('chapter_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('chapter_name', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('long_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course.course_id'], name='chapter_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('chapters')
    # ### end Alembic commands ###
