"""empty message

Revision ID: df878fa9671a
Revises: 76461081b9ca
Create Date: 2018-02-01 13:28:59.110201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df878fa9671a'
down_revision = '76461081b9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('name', sa.String(length=128), nullable=True))
    op.drop_constraint('buycar_ibfk_1', 'buycar', type_='foreignkey')
    op.drop_column('buycar', 'goods')
    op.drop_constraint('collect_ibfk_2', 'collect', type_='foreignkey')
    op.drop_column('collect', 'goods')
    op.drop_constraint('detail_ibfk_2', 'detail', type_='foreignkey')
    op.drop_column('detail', 'goods_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('goods_name', mysql.VARCHAR(length=512), nullable=True))
    op.create_foreign_key('detail_ibfk_2', 'detail', 'goods', ['goods_name'], ['name'])
    op.add_column('collect', sa.Column('goods', mysql.VARCHAR(length=512), nullable=True))
    op.create_foreign_key('collect_ibfk_2', 'collect', 'goods', ['goods'], ['name'])
    op.add_column('buycar', sa.Column('goods', mysql.VARCHAR(length=512), nullable=True))
    op.create_foreign_key('buycar_ibfk_1', 'buycar', 'goods', ['goods'], ['name'])
    op.drop_column('address', 'name')
    # ### end Alembic commands ###
