"""empty message

Revision ID: e4626fc6b126
Revises: d0cbfa7b8956
Create Date: 2018-02-28 15:24:58.800466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4626fc6b126'
down_revision = 'd0cbfa7b8956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'course', ['course_id'], ['course_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'course_id')
    # ### end Alembic commands ###
