"""empty message

Revision ID: f827a5867daa
Revises: 
Create Date: 2018-02-05 09:44:23.454746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f827a5867daa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('view', sa.Integer(), nullable=True),
    sa.Column('today_order', sa.Integer(), nullable=True),
    sa.Column('today_course', sa.Integer(), nullable=True),
    sa.Column('today_views', sa.Integer(), nullable=True),
    sa.Column('today_vip', sa.Integer(), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('course_num', sa.Integer(), nullable=True),
    sa.Column('view_num', sa.Integer(), nullable=True),
    sa.Column('user_num', sa.Integer(), nullable=True),
    sa.Column('local_people', sa.Integer(), nullable=True),
    sa.Column('max_people', sa.Integer(), nullable=True),
    sa.Column('max_people_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=512), nullable=True),
    sa.Column('school_address', sa.String(length=512), nullable=True),
    sa.Column('course_num', sa.Integer(), nullable=True),
    sa.Column('student_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_name')
    )
    op.create_table('tag_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('pwd', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.Column('image', sa.TEXT(), nullable=True),
    sa.Column('account_atatus', sa.String(length=4), nullable=True),
    sa.Column('activate', sa.String(length=4), nullable=True),
    sa.Column('ac_type', sa.String(length=4), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('member_grade', sa.String(length=4), nullable=True),
    sa.Column('account_point', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password_hash'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_user_addtime'), 'user', ['addtime'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=512), nullable=True),
    sa.Column('area', sa.String(length=512), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('remarks', sa.String(length=512), nullable=True),
    sa.Column('default_add', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DATETIME(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_add', sa.String(length=32), nullable=True),
    sa.Column('add_time', sa.DATETIME(), nullable=True),
    sa.Column('user_logs', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_logs'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_time', sa.DATETIME(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('f_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['f_name'], ['tag_list.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('t_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['t_name'], ['tags.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_name', sa.String(length=512), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('good_tag', sa.String(length=128), nullable=True),
    sa.Column('long_time', sa.String(length=128), nullable=True),
    sa.Column('study_num', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.String(length=512), nullable=True),
    sa.Column('chap_num', sa.Integer(), nullable=True),
    sa.Column('price', sa.FLOAT(precision=16), nullable=True),
    sa.Column('old_price', sa.FLOAT(precision=16), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('discount', sa.FLOAT(precision=32), nullable=True),
    sa.Column('add_time', sa.DATETIME(), nullable=True),
    sa.Column('skull_num', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.Column('view_num', sa.Integer(), nullable=True),
    sa.Column('comment_num', sa.Integer(), nullable=True),
    sa.Column('course_info', sa.Text(), nullable=True),
    sa.Column('share_link', sa.String(length=256), nullable=True),
    sa.Column('get_secure', sa.String(length=256), nullable=True),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['good_tag'], ['tag.name'], ),
    sa.ForeignKeyConstraint(['school_name'], ['school.school_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id'),
    sa.UniqueConstraint('course_name'),
    sa.UniqueConstraint('image')
    )
    op.create_table('buycar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_time', sa.DATETIME(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('price', sa.FLOAT(precision=16), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_car', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['user_car'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_time', sa.DATETIME(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['users'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('add_time', sa.DATETIME(), nullable=True),
    sa.Column('fab', sa.Integer(), nullable=True),
    sa.Column('replay', sa.Text(), nullable=True),
    sa.Column('comment_course_id', sa.Integer(), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['users'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_time', sa.DATETIME(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('orderId', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['orderId'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('good_course', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['good_course'], ['course.course_name'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_course')
    op.drop_table('detail')
    op.drop_table('comment')
    op.drop_table('collect')
    op.drop_table('buycar')
    op.drop_table('course')
    op.drop_table('tag')
    op.drop_table('tags')
    op.drop_table('orders')
    op.drop_table('log')
    op.drop_table('address')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_addtime'), table_name='user')
    op.drop_table('user')
    op.drop_table('tag_list')
    op.drop_table('school')
    op.drop_table('count')
    # ### end Alembic commands ###
