# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsId', models.IntegerField()),
                ('colorId', models.IntegerField()),
                ('sizeId', models.IntegerField()),
                ('count', models.IntegerField()),
                ('username', models.CharField(max_length=80, unique=True)),
            ],
        ),
    ]
