# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20171121_1838'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartitem',
            managers=[
            ],
        ),
    ]
